# Generated by Django 4.0.4 on 2022-08-10 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.ManyToManyField(to='verbes_app.table')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.CharField(blank=True, max_length=50)),
                ('preterit', models.CharField(blank=True, max_length=50)),
                ('participe_passe', models.CharField(blank=True, max_length=50)),
                ('francais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes_app.userprofile')),
                ('verbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verbes', to='verbes_app.verbe')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_table', to='verbes_app.table')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes_app.userprofile')),
                ('verbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbes_app.verbe')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verbes',
            field=models.ManyToManyField(related_name='verbes', through='verbes_app.UserVerbe', to='verbes_app.verbe'),
        ),
        migrations.AddField(
            model_name='table',
            name='verbes',
            field=models.ManyToManyField(to='verbes_app.verbe'),
        ),
    ]
