# Generated by Django 4.0.4 on 2022-04-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.CharField(blank=True, max_length=50)),
                ('preterit', models.CharField(blank=True, max_length=50)),
                ('participe_passe', models.CharField(blank=True, max_length=50)),
                ('francais', models.CharField(max_length=50)),
            ],
        ),
    ]
