# Generated by Django 4.0.4 on 2022-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verbes',
            new_name='Verbe',
        ),
    ]
