# Generated by Django 4.0.4 on 2022-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0002_rename_verbes_verbe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbes', models.ManyToManyField(to='verbes_app.verbe')),
            ],
        ),
    ]
