# Generated by Django 4.0.4 on 2022-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0004_verbe_done_verbe_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
