# Generated by Django 4.0.4 on 2022-05-18 10:01

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Table = apps.get_model('verbes_app', 'Table')
    VerbeList = apps.get_model('verbes_app', 'VerbeList')
    for table in Table.objects.all():
        for verbe in table.verbes.all():
            VerbeList(
                verbe=verbe,
                table=table
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0006_verbelist'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
