# Generated by Django 4.0.4 on 2022-05-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0007_auto_20220518_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='verbes',
        ),
    ]
