# Generated by Django 4.0.4 on 2022-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0008_remove_table_verbes'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='verbes',
            field=models.ManyToManyField(through='verbes_app.VerbeList', to='verbes_app.verbe'),
        ),
    ]
