# Generated by Django 4.0.4 on 2022-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0009_table_verbes'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbelist',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verbelist',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
