# Generated by Django 4.0.4 on 2022-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0010_verbelist_done_verbelist_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='verbes',
            field=models.ManyToManyField(related_name='tables', through='verbes_app.VerbeList', to='verbes_app.verbe'),
        ),
    ]
