# Generated by Django 4.0.4 on 2022-05-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbes_app', '0011_alter_table_verbes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbelist',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_verbes', to='verbes_app.table'),
        ),
    ]
